#cloud-config
users: 
  - name: ubuntu 
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin 
    home: /home/ubuntu 
    shell: /bin/bash 
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCirIXTGf/nrpg1mlNFdClQelCJk7ReZaNPglk0pSqV7t8wLpJ8jpOzmRQAeNnW7YHDtxxmfV6EJmGcE4MdJHctlRR/fy+uncXbjHzTAJh90JrxKG0IdRb1/4B3M3G59Z9r0Ra5Z1ZGyjb378CP5xSA6ReEnIOl+MH3lzry2ZK59MIdKnhUyA0KpDrUaXrADNn6ou01jC5379YSzyrIVhyi/BKRZbMxljBIlSa4Uq2W6Zyf1d/dd9ynkOYJACOlRGONnYCahbFD6zzzVE2XYTCgTc3gYjSF/0y9//uPxrkM4m7uX0/OX6SasqE1ibsUdGyTV0hRPrv0ia0ZknFFChw1
ssh_pwauth: false 
disable_root: false 
package_update: true  
packages: 
  - curl 
  - wget 
